name: CI

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master, ci ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Download love
      run: |
        curl -LO https://github.com/love2d/love/releases/download/11.3/love-11.3-win64.zip
        curl -LO https://github.com/love2d/love/releases/download/11.3/love-11.3-win32.zip
        7z x love-11.3-win64.zip
        7z x love-11.3-win32.zip
        copy love-11.3-win64/lua51.dll .
        copy love-11.3-win32/lua51.dll x86
    - name: Setup rust win32
      run: rustup target add i686-pc-windows-msvc
    - name: Build coldclear
      run: |
        cd cold-clear/c-api
        cargo build --release
        cargo build --release --target=i686-pc-windows-msvc
        cd ../..
        copy cold-clear/target/release/cold_clear.dll .
        copy cold-clear/target/i686-pc-windows-msvc/release/cold_clear.dll x86
    - name: Build ccloader
      run: |
        mingw32-make
        mingw32-make x86/CCloader.dll
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: win64
        path: |
          CCloader.dll
          cold_clear.dll
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: win32
        path: |
          x86/CCloader.dll
          x86/cold_clear.dll
